[package]

name = "hash_ring"
version = "0.1.6"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
documentation = "https://docs.rs/hash_ring"
repository = "https://github.com/mattnenterprise/rust-hash-ring"
homepage = "https://github.com/mattnenterprise/rust-hash-ring"
description = "Consistent Hashing library for Rust"
readme = "README.md"
license = "MIT"

keywords = ["consistent-hashing", "hash-ring"]
categories = ["data-structures"]

[badges]
travis-ci = { repository = "mattnenterprise/rust-imap" }
coveralls = { repository = "mattnenterprise/rust-imap", branch = "master", service = "github" }

[dependencies]
md5 = "0.3.5"
